# Generated by Django 5.2.1 on 2026-05-16 22:18

import apps.surveys.domain.entities
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[(apps.surveys.domain.entities.StatusPesquisa['RASCUNHO'], 'Rascunho'), (apps.surveys.domain.entities.StatusPesquisa['ABERTA'], 'Aberta'), (apps.surveys.domain.entities.StatusPesquisa['FECHADA'], 'Fechada')], default=apps.surveys.domain.entities.StatusPesquisa['RASCUNHO'], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pesquisa',
                'verbose_name_plural': 'pesquisas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='surveys.pesquisa')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('ordem', models.PositiveSmallIntegerField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='surveys.questao')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='RespostaRespondente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='surveys.pesquisa')),
                ('respondente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pesquisa', 'respondente')},
            },
        ),
        migrations.CreateModel(
            name='RespostaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.opcao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.questao')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='surveys.respostarespondente')),
            ],
            options={
                'unique_together': {('resposta', 'questao')},
            },
        ),
    ]
